## Pytorch Tutorial
# Tensors Basics
A tensor is a generalization of vectors and matrices and is easily understood as a multidimensional array.It is a term and set of techniques known in machine learning in the training and operation of deep learning models can be described in terms of tensors. In many cases tensors are used as a replacement for NumPy to use the power of GPUs.

Tensors are a type of data structure used in linear algebra, and like vectors and matrices, you can calculate arithmetic operations with tensors.

In [1]:
import torch              # matrix multiplication can be performed easily with torch

In [2]:
torch.__version__        #  Here in oup_put '+cpu'-iam unsing pytorch on cpu 
                         # iam not having Nvidia GPU so i cant utilize the computational power of GPU

'2.0.1+cpu'

In [3]:
import numpy as np
lst = [3,4,5,6]
arr = np.array(lst)            # np.array which will store the original data 
arr

array([3, 4, 5, 6])

In [4]:
arr.dtype

dtype('int32')

In [5]:
lst[2] = 10

In [6]:
print(lst)                        # lst is updated [3,4,5,6] --> [3, 4, 10, 6]
print(arr)                        # arr is not updated - np.array() function stores original data

[3, 4, 10, 6]
[3 4 5 6]


# convert Numpy to Pytorch Tensors

Tensors are similar to NumPy arrays, but they come with additional capabilities, such as automatic differentiation for gradient computations and seamless integration with GPUs for accelerated computations.

In [7]:
tensor = torch.from_numpy(arr)          # 'torch.from_numpy()' to create a PyTorch tensor from a NumPy array
tensor

tensor([3, 4, 5, 6], dtype=torch.int32)

In [8]:
# Indexing similar to numpy
print(tensor[:2])
print(tensor[: : 2])

tensor([3, 4], dtype=torch.int32)
tensor([3, 5], dtype=torch.int32)


In [9]:
# Disadvantage of from_numpy. The array and tensor uses the same memory location

tensor[3] = 100
print(tensor)                                       
print(arr)                                  # original data is updated because of same memory location

tensor([  3,   4,   5, 100], dtype=torch.int32)
[  3   4   5 100]


In [10]:
# prevent this by using torch.tensor

tensor_arr = torch.tensor(arr)             # torch.tensor() always copies data
tensor_arr

tensor([  3,   4,   5, 100], dtype=torch.int32)

In [11]:
tensor_arr[2] = 200
print(tensor_arr)
print(arr)                                       

tensor([  3,   4, 200, 100], dtype=torch.int32)
[  3   4   5 100]


we can create tensors by using in-built function that are present inside torch


In [12]:
torch.zeros(2,3, dtype = torch.int32)           #zero  - built in function in torch
                                                #(2,3) - shape of the matrix 
                                                #dtype = torch.int32 - Data type

tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)

In [13]:
torch.ones(3,3, dtype = torch.float64)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [14]:
torch.rand(3,2)

tensor([[0.1967, 0.0849],
        [0.8353, 0.0059],
        [0.2001, 0.7212]])

## Arithmetic Operation

In [15]:
m1 = torch.tensor([1,2,3],dtype = torch.float)
m2 = torch.tensor([5,6,7], dtype = torch.float)

In [16]:
print(m1+m2)
print(torch.add(m1,m2))        # torch.add - inbuilt function 

tensor([ 6.,  8., 10.])
tensor([ 6.,  8., 10.])


In [18]:
torch.add(m1, m2, out=m)        # 'out = None' what ever operation is done that will store in 'm' variable

tensor([ 6.,  8., 10.])

In [19]:
m

tensor([ 6.,  8., 10.])

In [20]:
## some more operations
## tensor[6.,  8., 10.]
torch.add(m1,m2).sum()

tensor(24.)

In [21]:
# Multiplication operation
m1.mul(m2)                        # 1*5 , 2*6 , 3*7

tensor([ 5., 12., 21.])

In [22]:
# Dot Product
m1.dot(m2)                      # 1*5 + 2*6 + 3*7

tensor(38.)

## Matrix Multiplication

In [23]:
x = torch.tensor([[2,5,6],[4,6,7]],dtype = torch.int)
y = torch.tensor([[3,4],[5,6],[7,5]],dtype = torch.int)

In [24]:
print(torch.matmul(x,y))
print(torch.mm(x,y))
print(x@y)

tensor([[73, 68],
        [91, 87]], dtype=torch.int32)
tensor([[73, 68],
        [91, 87]], dtype=torch.int32)
tensor([[73, 68],
        [91, 87]], dtype=torch.int32)
